# Generated by Django 3.2.12 on 2022-09-15 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rendiciones', '0003_rename_clientes_rendicion_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='RendicionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField()),
                ('monto_neto', models.CharField(blank=True, max_length=100, null=True)),
                ('monto_iva', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='rendicion',
            name='encargado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='RendicionDetalleArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('ruta', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rendicion_detalle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rendiciones_detalle_archivo', to='rendiciones.rendiciondetalle')),
            ],
        ),
        migrations.AddField(
            model_name='rendiciondetalle',
            name='rendicion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rendiciones_detalle_rendicion', to='rendiciones.rendicion'),
        ),
        migrations.CreateModel(
            name='RendicionArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('ruta', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rendicion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imagenes_rendicion', to='rendiciones.rendicion')),
            ],
        ),
    ]
