# Generated by Django 3.2.12 on 2022-09-15 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rendiciones', '0004_auto_20220915_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='RendicionKilometraje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('kilometraje_inicial', models.CharField(blank=True, max_length=100, null=True)),
                ('kilometraje_final', models.CharField(blank=True, max_length=100, null=True)),
                ('img_km_inicial', models.TextField(blank=True, null=True)),
                ('img_km_final', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rendicion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rendiciones_kilometraje_rendicion', to='rendiciones.rendicion')),
            ],
        ),
    ]
