# Generated by Django 3.2.12 on 2022-09-15 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rendiciones', '0005_rendicionkilometraje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendicionkilometraje',
            name='descripcion',
        ),
    ]
