# Generated by Django 3.2.12 on 2022-09-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendiciones', '0006_remove_rendicionkilometraje_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendicion',
            name='img_km_final',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rendicion',
            name='img_km_inicial',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rendicion',
            name='kilometraje_final',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rendicion',
            name='kilometraje_inicial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='RendicionKilometraje',
        ),
    ]
