# Generated by Django 3.2.12 on 2022-09-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendiciones', '0007_auto_20220915_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendicion',
            name='img_km_final',
            field=models.ImageField(blank=True, null=True, upload_to='rendiciones'),
        ),
        migrations.AlterField(
            model_name='rendicion',
            name='img_km_inicial',
            field=models.ImageField(blank=True, null=True, upload_to='rendiciones'),
        ),
    ]
