# Generated by Django 3.2.12 on 2022-09-28 13:42

import apps.rendiciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendiciones', '0009_auto_20220928_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendiciondetallearchivo',
            name='rendicion_detalle',
        ),
        migrations.AlterField(
            model_name='rendiciondetalle',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=apps.rendiciones.models.file_path_detalle),
        ),
        migrations.DeleteModel(
            name='RendicionArchivo',
        ),
        migrations.DeleteModel(
            name='RendicionDetalleArchivo',
        ),
    ]
