# Generated by Django 3.2.12 on 2022-10-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendiciones', '0010_auto_20220928_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendicion',
            name='sitios_cliente',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
