# Generated by Django 3.2.12 on 2022-10-03 11:44

import apps.rendiciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendiciones', '0012_auto_20221003_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendiciondetalle',
            name='img_km_final',
            field=models.ImageField(blank=True, null=True, upload_to=apps.rendiciones.models.file_path_detalle),
        ),
        migrations.AlterField(
            model_name='rendiciondetalle',
            name='img_km_inicial',
            field=models.ImageField(blank=True, null=True, upload_to=apps.rendiciones.models.file_path_detalle),
        ),
    ]
