# Generated by Django 3.2.12 on 2022-10-03 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rendiciones', '0014_auto_20221003_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendiciondetalle',
            name='tipo_gasto',
        ),
    ]
