# Generated by Django 3.2.12 on 2022-10-03 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rendiciones', '0015_remove_rendiciondetalle_tipo_gasto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipoDeGasto',
        ),
    ]
