# Generated by Django 3.2.12 on 2022-10-03 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rendiciones', '0019_rendiciondetalle_sitios_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rendiciondetalle',
            old_name='documento',
            new_name='imagen',
        ),
    ]
