# Generated by Django 3.2.12 on 2022-10-03 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rendiciones', '0020_rename_documento_rendiciondetalle_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rendiciondetalle',
            old_name='imagen',
            new_name='documento',
        ),
    ]
