# Generated by Django 3.2.12 on 2022-10-03 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rendiciones', '0023_rendiciondetalle_tipo_gasto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rendiciondetalle',
            old_name='monto_iva',
            new_name='monto',
        ),
        migrations.RemoveField(
            model_name='rendiciondetalle',
            name='monto_neto',
        ),
    ]
