# Generated by Django 3.2.12 on 2022-10-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendiciones', '0026_remove_rendiciondetalle_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendiciondetalle',
            name='fecha',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
