# Generated by Django 3.2.12 on 2022-10-03 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rendiciones', '0032_rendiciondetalle_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendiciondetalle',
            name='is_region',
        ),
    ]
