# Generated by Django 3.2.12 on 2022-10-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendiciones', '0033_remove_rendiciondetalle_is_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendiciondetalle',
            name='is_region',
            field=models.BooleanField(default=False),
        ),
    ]
